language: php

sudo: false
cache:
    directories:
        - $HOME/.composer/cache/files
        - $HOME/symfony-bridge/.phpunit

services:
  - mysql
  - postgresql
  - xvfb
  
env:
    global:
        - PANTHER_WEB_SERVER_DIR=$TRAVIS_BUILD_DIR/tests/public
        - PHPUNIT_FLAGS="-v"
        - SYMFONY_PHPUNIT_DIR="$HOME/symfony-bridge/.phpunit"
  
matrix:
    fast_finish: true
    include:
        - php: 7.2
          env: DB=mysql SYMFONY=4.4 XDEBUG=0
        - php: 7.2
          env: DB=mysql SYMFONY=4.4 XDEBUG=1
        - php: 7.2
          env: DB=pgsql SYMFONY=4.4 XDEBUG=0
        - php: 7.2
          env: DB=pgsql SYMFONY=4.4 XDEBUG=1
        - php: 7.2
          env: DB=sqlite3 SYMFONY=4.4 XDEBUG=0
        - php: 7.2
          env: DB=sqlite3 SYMFONY=4.4 XDEBUG=1
        - php: 7.3
          env: DB=mysql SYMFONY=4.4 XDEBUG=0
        - php: 7.3
          env: DB=mysql SYMFONY=4.4 XDEBUG=1
        - php: 7.3
          env: DB=pgsql SYMFONY=4.4 XDEBUG=0
        - php: 7.3
          env: DB=pgsql SYMFONY=4.4 XDEBUG=1
        - php: 7.3
          env: DB=sqlite3 SYMFONY=4.4 XDEBUG=0
        - php: 7.3
          env: DB=sqlite3 SYMFONY=4.4 XDEBUG=1
          
    allow_failures:
        #Sqlite fails on comparision date (equals)
        - php: 7.2
          env: DB=mysql SYMFONY=4.4 XDEBUG=1
        - php: 7.3
          env: DB=mysql SYMFONY=4.4 XDEBUG=1
        - php: 7.2
          env: DB=pgsql SYMFONY=4.4 XDEBUG=1
        - php: 7.3
          env: DB=pgsql SYMFONY=4.4 XDEBUG=1
        - php: 7.2
          env: DB=sqlite3 SYMFONY=4.4 XDEBUG=0
        - php: 7.2
          env: DB=sqlite3 SYMFONY=4.4 XDEBUG=1
        - php: 7.3
          env: DB=sqlite3 SYMFONY=4.4 XDEBUG=0
        - php: 7.3
          env: DB=sqlite3 SYMFONY=4.4 XDEBUG=1

    exclude:
    #- php: hhvm
    #  env: DB=pgsql

addons:
  chrome: stable
  apt:
    packages:
      - apache2 libapache2-mod-fastcgi make ant
      
before_script:
  - sudo /bin/dd if=/dev/zero of=/var/swap.1 bs=1M count=1024
  - sudo /sbin/mkswap /var/swap.1
  - sudo /sbin/swapon /var/swap.1

  - if [[ ! $TRAVIS_PHP_VERSION =~ hhvm ]]; then phpenv config-add ./tests/build/travis.php.ini; fi
  - if [[ ! $TRAVIS_PHP_VERSION =~ hhvm ]] ; then pecl channel-update pecl.php.net; fi;
  - if [[ ! $TRAVIS_PHP_VERSION =~ ^hhvm ]] ; then echo "yes" | pecl install channel://pecl.php.net/apcu || true; fi
  - if [[ ! $TRAVIS_PHP_VERSION =~ ^hhvm ]] ; then echo "yes" | pecl install channel://pecl.php.net/apcu_bc || true; fi
  #- cat ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  #- cat ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
   
  - if [[ ! $TRAVIS_PHP_VERSION =~ ^hhvm ]] ; then sed -i '/max_execution_time=1800/d' ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini; fi
  - if [[ ! $TRAVIS_PHP_VERSION =~ ^hhvm ]] ; then sed -i '/extension="apc.so"/d' ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini; fi
  - if [[ ! $TRAVIS_PHP_VERSION =~ ^hhvm ]] ; then sed -i '/extension="apcu.so"/d' ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini; fi
  - if [[ ! $TRAVIS_PHP_VERSION =~ ^hhvm ]] ; then phpenv config-add ./tests/build/ini/apc-7.ini; fi
  #- cat ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - if [[ ! $TRAVIS_PHP_VERSION =~ ^hhvm ]]; then sudo cp ~/.phpenv/versions/$(phpenv version-name)/etc/php-fpm.conf.default ~/.phpenv/versions/$(phpenv version-name)/etc/php-fpm.conf; fi
  - if [[ ! $TRAVIS_PHP_VERSION =~ ^hhvm ]]; then sudo cp ./tests/build/www.conf ~/.phpenv/versions/$(phpenv version-name)/etc/php-fpm.d/; fi
  - sudo a2enmod rewrite actions fastcgi alias
  - if [[ ! $TRAVIS_PHP_VERSION =~ ^hhvm ]]; then echo "cgi.fix_pathinfo = 1" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini; fi
  - if [[ ! $TRAVIS_PHP_VERSION =~ ^hhvm ]]; then sudo sed -i -e "s,www-data,travis,g" /etc/apache2/envvars; fi
  - if [[ ! $TRAVIS_PHP_VERSION =~ ^hhvm ]]; then sudo chown -R travis:travis /var/lib/apache2/fastcgi; fi
  - if [[ ! $TRAVIS_PHP_VERSION =~ ^hhvm ]]; then ~/.phpenv/versions/$(phpenv version-name)/sbin/php-fpm; fi
  - if [[ ! $TRAVIS_PHP_VERSION =~ ^hhvm ]]; then sudo cp -f ./tests/build/travis-ci-apache /etc/apache2/sites-available/000-default.conf; fi
  - if [[ ! $TRAVIS_PHP_VERSION =~ ^hhvm ]]; then sudo sed -e "s?%TRAVIS_BUILD_DIR%?$(pwd)?g" --in-place /etc/apache2/sites-available/000-default.conf; fi
  - sudo sed -i 's/Listen 80/Listen 8000/' /etc/apache2/ports.conf
  - sudo sed -i 's/NameVirtualHost \*:80/NameVirtualHost \*:8000/' /etc/apache2/ports.conf
  - sudo service apache2 restart
  
  - if [[ "$DB" == "pgsql" ]]; then echo "PROVISIONING WITH PostgreSQL"; fi
  - if [[ "$DB" == "pgsql" ]]; then cp -f ./tests/build/.env.pgsql $TRAVIS_BUILD_DIR/tests/.env; fi
  - if [[ "$DB" == "pgsql" ]]; then cp -f ./tests/build/bicore.pgsql.yml $TRAVIS_BUILD_DIR/tests/config/packages/bicore.yml; fi
  - if [[ "$DB" == "pgsql" ]]; then psql -c 'create database unittest;' -U postgres; fi
  - if [[ "$DB" == "pgsql" ]]; then psql -c "CREATE USER biuser WITH PASSWORD 'biuserpwd';" -U postgres; fi
  - if [[ "$DB" == "pgsql" ]]; then psql -c "GRANT ALL PRIVILEGES ON DATABASE unittest TO biuser;" -U postgres; fi
  - if [[ "$DB" == "pgsql" ]]; then psql -c "ALTER USER biuser CREATEDB;" -U postgres; fi
  - if [[ "$DB" == "pgsql" ]]; then psql -c "alter role biuser superuser;" -U postgres; fi
  
  - if [[ "$DB" == "mysql" ]]; then echo "PROVISIONING WITH MySQL"; fi
  - if [[ "$DB" == "mysql" ]]; then cp -f ./tests/build/.env.mysql $TRAVIS_BUILD_DIR/tests/.env; fi
  - if [[ "$DB" == "mysql" ]]; then mysql --version; fi
  - if [[ "$DB" == "mysql" ]]; then mysql -e "CREATE DATABASE unittest;" -uroot; fi
  - if [[ "$DB" == "mysql" ]]; then mysql -u root -e "CREATE USER 'biuser'@'localhost' IDENTIFIED BY 'biuserpwd';"; fi
  - if [[ "$DB" == "mysql" ]]; then mysql -u root -e "GRANT ALL ON unittest.* TO 'biuser'@'localhost';"; fi
  
  - if [[ "$DB" == "sqlite3" ]]; then echo "PROVISIONING WITH Sqlite3"; fi
  - if [[ "$DB" == "sqlite3" ]]; then cp -f ./tests/build/.env.sqlite $TRAVIS_BUILD_DIR/tests/.env; fi
  
  #- if [[ $SYMFONY == "5.0" ]]; then sed -i -e "s,4.4.\*,5.0.\*,g" $TRAVIS_BUILD_DIR/composer.json; fi
  #- if [[ $SYMFONY == "5.0" ]]; then sed -i '\|"sensio\/distribution-bundle"|d' $TRAVIS_BUILD_DIR/composer.json; fi
  #- if [[ $SYMFONY == "5.0" ]]; then sed -i '\"SensioDistributionBundle"d' $TRAVIS_BUILD_DIR/tests/config/bundles.php; fi

  - chmod +x bin/console
  - if [[ "$XDEBUG" == "0" ]]; then phpenv config-rm xdebug.ini; fi
  - php -i

script:
  - travis_wait 40 ant
  #- PANTHER_WEB_SERVER_DIR=/src/php/BiCoreBundle/tests/public PANTHER_NO_HEADLESS=1 vendor/bin/simple-phpunit -c tools/phpunit/phpunit.xml.dist --filter test20AdminpanelGenerateBundle

after_success:
  - if [[ "$XDEBUG" == "1" ]]; then php vendor/bin/php-coveralls -v; fi
  - if [[ "$XDEBUG" == "1" ]]; then wget https://scrutinizer-ci.com/ocular.phar -t 3; fi
  - if [[ "$XDEBUG" == "1" ]]; then php ocular.phar code-coverage:upload --format=php-clover build/artifacts/coverage/clover.xml; fi
  - rm tests/var/cache/dbtest.sqlite
  #- php tests/bin/console server:stop --env=test
  #- kill `ps -ef | grep selenium | awk '{ print $2 }'`

after_failure:
  - sudo cat /var/log/apache2/error.log
  - sudo cat /var/log/apache2/access.log
  - sudo cat /var/log/apache2/other_vhosts_access.log
  - sudo cat /var/log/apache2/bi_error.log
  - sudo cat /var/log/apache2/bi_access.log
  - sudo cat $TRAVIS_BUILD_DIR/tests/var/logs/test.log
  #- sudo cat /tmp/screenshot.txt

notifications:
  email:
  - andrea.manzi@comune.fi.it
