#!/usr/bin/env php
<?php

use Symfony\Bundle\FrameworkBundle\Console\Application;

set_time_limit(0);

function includeIfExists($file)
{
    if (file_exists($file)) {
        return include $file;
    }
}

if ((!$loader = includeIfExists(__DIR__.'/vendor/autoload.php')) && (!$loader = includeIfExists(__DIR__.'/../../autoload.php'))) {
    die('You must set up the project dependencies, run the following commands:'.PHP_EOL.
        'curl -sS https://getcomposer.org/installer | php'.PHP_EOL.
        'php composer.phar install'.PHP_EOL);
}

$kernel = new AppKernel("dev", false);
$application = new Application($kernel);

$command = new Cdf\PannelloAmministrazioneBundle\Command\ChecksrcCommand();

$application->add($command);

$application->setDefaultCommand($command->getName(), true);
$application->run();
