services:
#    fi_pannello_amministrazione.example:
#        class: %fi_pannello_amministrazione.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
        public: false       # Allows optimizing the container by removing unused services; this also means
                            # fetching services directly from the container via $container->get() won't work.
                            # The best practice is to be explicit about your dependencies anyway.
            
    pannelloamministrazione.commands:
        class: Cdf\PannelloAmministrazioneBundle\DependencyInjection\PannelloamministrazioneCommands
        public: true
        arguments:
            ['@service_container']

    pannelloamministrazione.utils:
        alias: Cdf\PannelloAmministrazioneBundle\DependencyInjection\PannelloAmministrazioneUtils
        public: true
        
    Cdf\PannelloAmministrazioneBundle\DependencyInjection\PannelloAmministrazioneUtils:
        class: Cdf\PannelloAmministrazioneBundle\DependencyInjection\PannelloAmministrazioneUtils
        public: true
        arguments:
            ['@service_container']

    pannelloamministrazione.projectpath:
        alias: Cdf\PannelloAmministrazioneBundle\DependencyInjection\ProjectPath
        public: true
    
    Cdf\PannelloAmministrazioneBundle\DependencyInjection\ProjectPath:
        class: Cdf\PannelloAmministrazioneBundle\DependencyInjection\ProjectPath
        public: false
        arguments:
            $projectDir: '%kernel.project_dir%'
            $cacheDir: '%kernel.cache_dir%'
            $logsDir: '%kernel.logs_dir%'

    pannelloamministrazione.generatorhelper:
        alias: Cdf\PannelloAmministrazioneBundle\DependencyInjection\GeneratorHelper
        public: true

    Cdf\PannelloAmministrazioneBundle\DependencyInjection\GeneratorHelper:
        class: Cdf\PannelloAmministrazioneBundle\DependencyInjection\GeneratorHelper
        public: false
        arguments:
            ['@service_container']

    pannelloamministrazione.command.generateormentities:
        class: Cdf\PannelloAmministrazioneBundle\Command\GenerateOrmEntitiesCommand
        public: false
        tags:
            -  { name: console.command, command: pannelloamministrazione:generateormentities  }
            
    cdf.bicorebundle.generateormentities:
        alias: pannelloamministrazione.command.generateormentities
        public: true

    pannelloamministrazione.command.generateform:
        class: Cdf\PannelloAmministrazioneBundle\Command\GenerateFormCommand
        public: false
        tags:
            -  { name: console.command }            

    pannelloamministrazione.command.checkgitversion:
        class: Cdf\PannelloAmministrazioneBundle\Command\CheckgitversionCommand
        public: false
        tags:
            -  { name: console.command }            

    pannelloamministrazione.command.checksrc:
        class: Cdf\PannelloAmministrazioneBundle\Command\ChecksrcCommand
        public: false
        tags:
            -  { name: console.command }

    #Controllers
    pannelloamministrazione.controller:
        class: Cdf\PannelloAmministrazioneBundle\Controller\PannelloAmministrazioneController
        public: true
        arguments: 
            $appname: "%bi_core.appname%"
            $lockfile: "%bi_core.lockfile%"
