services:
#    fi_pannello_amministrazione.example:
#        class: %fi_pannello_amministrazione.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
        public: false       # Allows optimizing the container by removing unused services; this also means
                            # fetching services directly from the container via $container->get() won't work.
                            # The best practice is to be explicit about your dependencies anyway.
            
    pannelloamministrazione.commands:
        alias: Cdf\PannelloAmministrazioneBundle\Utils\Commands
        public: true
            
    Cdf\PannelloAmministrazioneBundle\Utils\Commands:
        public: false

    pannelloamministrazione.utils:
        alias: Cdf\PannelloAmministrazioneBundle\Utils\Utility
        public: true
        
    Cdf\PannelloAmministrazioneBundle\Utils\Utility:
        class: Cdf\PannelloAmministrazioneBundle\Utils\Utility
        arguments: ["@kernel"]
        public: false

    pannelloamministrazione.projectpath:
        alias: Cdf\PannelloAmministrazioneBundle\Utils\ProjectPath
        public: true
    
    Cdf\PannelloAmministrazioneBundle\Utils\ProjectPath:
        public: false
        calls:
             - [setRootDir, ['%kernel.project_dir%']]
             - [setCacheDir, ['%kernel.cache_dir%']]
             - [setLogsDir, ['%kernel.logs_dir%']]

    pannelloamministrazione.generatorhelper:
        alias: Cdf\PannelloAmministrazioneBundle\Utils\GeneratorHelper
        public: true

    Cdf\PannelloAmministrazioneBundle\Utils\GeneratorHelper:
        public: false

    pannelloamministrazione.command.generateormentities:
        class: Cdf\PannelloAmministrazioneBundle\Command\GenerateOrmEntitiesCommand
        public: false
        tags:
            -  { name: console.command  }
            
    pannelloamministrazione.generateormentities:
        alias: pannelloamministrazione.command.generateormentities
        public: true

    pannelloamministrazione.command.generateform:
        class: Cdf\PannelloAmministrazioneBundle\Command\GenerateFormCommand
        public: false
        arguments: ["@kernel"]
        tags:
            -  { name: console.command }

    pannelloamministrazione.generateform:
        alias: pannelloamministrazione.command.generateform
        public: true

    pannelloamministrazione.command.checkgitversion:
        class: Cdf\PannelloAmministrazioneBundle\Command\CheckgitversionCommand
        public: false
        tags:
            -  { name: console.command }            

    pannelloamministrazione.command.checksrc:
        class: Cdf\PannelloAmministrazioneBundle\Command\ChecksrcCommand
        public: false
        tags:
            -  { name: console.command }

    #Controllers
    pannelloamministrazione.controller:
        class: Cdf\PannelloAmministrazioneBundle\Controller\PannelloAmministrazioneController
        public: true
        arguments: 
            $appname: "%bi_core.appname%"
            $lockfile: "%bi_core.lockfile%"
