BiCoreBundle_Funzioni:
    resource: "@BiCoreBundle/Resources/config/routing/funzioni.yml"
    prefix:   /funzioni

BiCoreBundle_exportxls:
    path:  /{controller}/exportxls
    defaults: { _controller: "cdf.bicorebundle.controller.ficontroller::exportXls" }
        
BiCoreBundle_Ruoli:
    resource: "@BiCoreBundle/Resources/config/routing/ruoli.yml"
    prefix:   /Ruoli
        
BiCoreBundle_Operatori:
    resource: "@BiCoreBundle/Resources/config/routing/operatori.yml"
    prefix:   /Operatori
    
BiCoreBundle_Permessi:
    resource: "@BiCoreBundle/Resources/config/routing/permessi.yml"
    prefix:   /Permessi
    
BiCoreBundle_Colonnetabelle:
    resource: "@BiCoreBundle/Resources/config/routing/colonnetabelle.yml"
    prefix:   /Colonnetabelle

BiCoreBundle_Opzionitabelle: 
  resource: "@BiCoreBundle/Resources/config/routing/opzionitabelle.yml"
  prefix: /Opzionitabelle

BiCoreBundle_Menuapplicazione: 
  resource: "@BiCoreBundle/Resources/config/routing/menuapplicazione.yml"
  prefix: /Menuapplicazione

BiCoreBundle_Storicomodifiche:
    resource: "@BiCoreBundle/Resources/config/routing/storicomodifiche.yml"
    prefix:   /Storicomodifiche
    
fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"


