services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
        public: false       # Allows optimizing the container by removing unused services; this also means
                            # fetching services directly from the container via $container->get() won't work.
                            # The best practice is to be explicit about your dependencies anyway.

    #twig extension
    cdf.bicorebundle.twig.extension.asset:
        class: Cdf\BiCoreBundle\Twig\Extension\AssetExtension
        arguments: ['%kernel.project_dir%']
        tags:
            - { name: twig.extension }

    cdf.bicorebundle.twig.extension.menu:
        class: Cdf\BiCoreBundle\Twig\Extension\MenuExtension
        arguments: [ '@doctrine.orm.entity_manager', '@router', '@security.token_storage', '%kernel.project_dir%' ]
        tags:
            - { name: twig.extension }

    cdf.bicorebundle.twig.extension.objecttotabella:
        alias: Cdf\BiCoreBundle\Twig\Extension\ObjectToTabellaExtension
        public: true
            
    Cdf\BiCoreBundle\Twig\Extension\ObjectToTabellaExtension:
        class: Cdf\BiCoreBundle\Twig\Extension\ObjectToTabellaExtension
        public: false
        arguments: 
            $tableprefix: "%bi_core.table_prefix%"

        tags:
            - { name: twig.extension }
            
    cdf.bicorebundle.twig.extension.utilita:
        class: Cdf\BiCoreBundle\Twig\Extension\UtilitaExtension
        arguments: ["@service_container"]
        tags:
          - { name: twig.extension }

    cdf.bicorebundle.twig.extension.headertabella:
        class: Cdf\BiCoreBundle\Twig\Extension\HeaderTabellaExtension
        tags:
          - { name: twig.extension }

    #Informazioni connessione database su Web Debug Toolbar
    cdf.bicorebundle.collector.databaseinfo:
        class: Cdf\BiCoreBundle\Collector\DatabaseInfoDataCollector
        tags:
            - { name: data_collector , template: "@BiCore/Collector/databaseInfo", id: "databaseInfo" }
            
    #Utility database
    cdf.bicorebundle.utility.database:
        alias: Cdf\BiCoreBundle\Utils\Database\DatabaseUtils
        public: true
    
    Cdf\BiCoreBundle\Utils\Database\DatabaseUtils:
        class: Cdf\BiCoreBundle\Utils\Database\DatabaseUtils
        arguments: [ '@kernel', '@doctrine.orm.entity_manager' ]
        public: false
    
    #Permessi Utils
    cdf.bicorebundle.permessi:
        alias: Cdf\BiCoreBundle\Service\Permessi\PermessiManager
        public: true
        
    Cdf\BiCoreBundle\Service\Permessi\PermessiManager:
        arguments: [ '@doctrine.orm.entity_manager', '@security.token_storage' ]
        public: false
        
    #Utility entities
    cdf.bicorebundle.utility.entity:
        alias: Cdf\BiCoreBundle\Utils\Entity\EntityUtils
        public: true
    
    Cdf\BiCoreBundle\Utils\Entity\EntityUtils:
        class: Cdf\BiCoreBundle\Utils\Entity\EntityUtils
        arguments: [ '@doctrine.orm.entity_manager' ]
        public: false
            
    Cdf\BiCoreBundle\Utils\Entity\Finder:
        arguments: [ '@doctrine.orm.entity_manager' ]
        public: false

    Cdf\BiCoreBundle\Utils\FieldType\FieldTypeUtils:
        public: false

    #Utility tabelle di sistema bi
    cdf.bicorebundle.utility.entity.system:
        alias: Cdf\BiCoreBundle\Utils\Entity\BiCoreSystemTablesUtils
        public: true
    
    Cdf\BiCoreBundle\Utils\Entity\BiCoreSystemTablesUtils:
        class: Cdf\BiCoreBundle\Utils\Entity\BiCoreSystemTablesUtils
        public: false
        arguments: [ '@doctrine.orm.entity_manager' ]
        
    Cdf\BiCoreBundle\Utils\Arrays\ArrayUtils:
        public: false

    #Utility export excel tabelle
    cdf.bicorebundle.utils.export.tabellaxls:
        alias: Cdf\BiCoreBundle\Utils\Export\TabellaXls
        public: true
        
    Cdf\BiCoreBundle\Utils\Export\TabellaXls:
        public: false
        arguments: 
            $tableprefix: "%bi_core.table_prefix%"

    #subscriber per aggiungere un suffisso alle tabelle di bi
    cdf.bicorebundle.subscriber.tableprefix:
        class: Cdf\BiCoreBundle\Subscriber\TablePrefixSubscriber
        arguments: 
            $tableprefix: "%bi_core.table_prefix%"
        tags:
            - { name: doctrine.event_subscriber }
            
    #subscriber per aggiungere uno schema alle tabelle di bi
    cdf.bicorebundle.subscriber.schemaprefix:
        class: Cdf\BiCoreBundle\Subscriber\TableSchemaSubscriber
        arguments: 
            $schemaprefix: "%bi_core.table_schema%"
        tags:
            - { name: doctrine.event_subscriber }

    #Entity type hidden
    cdf.bicorebundle.entitytype.hidden:
        class: Cdf\BiCoreBundle\Form\Type\EntityHiddenType
        arguments: ["@doctrine.orm.entity_manager"]
        tags:
        - { name: form.type, alias: entity_hidden }
        
    cdf.bicorebundle.utils.entity.doctrinefieldreader:
        alias: Cdf\BiCoreBundle\Utils\Entity\DoctrineFieldReader
        public: true
        
    Cdf\BiCoreBundle\Utils\Entity\DoctrineFieldReader:
        class: Cdf\BiCoreBundle\Utils\Entity\DoctrineFieldReader
        public: false
        arguments: 
            $tableprefix: "%bi_core.table_prefix%"
        
    FOS\UserBundle\Util\UserManipulator:
        alias: fos_user.util.user_manipulator
        
    #listener
    cdf.bicorebundle.kernel.listener.maintenance:
        class: Cdf\BiCoreBundle\Listener\MaintenanceListener
        arguments: 
            - "%bi_core.lockfile%"
        tags:
            - { name: kernel.event_listener, event: kernel.response, method: onKernelResponse }
            
    #Controllers
    cdf.bicorebundle.controller.ficontroller:
        alias: Cdf\BiCoreBundle\Controller\FiController
        public: true

    Cdf\BiCoreBundle\Controller\FiController:
        public: false
        calls:
            - method: setTabellaxls
              arguments:
                  - '@cdf.bicorebundle.utils.export.tabellaxls'
        #tags: ['controller.service_arguments']
        
    cdf.bicorebundle.controller.operatori:
        class: Cdf\BiCoreBundle\Controller\OperatoriController
        bind:
            # for any $logger argument, pass this specific service
            $logger: '@logger'
            $permessi: '@cdf.bicorebundle.permessi'
            $usermanipulator: '@fos_user.util.user_manipulator'
            
    cdf.bicorebundle.controller.permessi:
        class: Cdf\BiCoreBundle\Controller\PermessiController
    
    cdf.bicorebundle.controller.ruoli:
        class: Cdf\BiCoreBundle\Controller\RuoliController
    
    cdf.bicorebundle.controller.opzionitabelle:
        class: Cdf\BiCoreBundle\Controller\OpzionitabelleController

    cdf.bicorebundle.controller.menuapplicazione:
        class: Cdf\BiCoreBundle\Controller\MenuapplicazioneController

    cdf.bicorebundle.controller.colonnetabelle:
        class: Cdf\BiCoreBundle\Controller\ColonnetabelleController

    cdf.bicorebundle.controller.storicomodifiche:
        class: Cdf\BiCoreBundle\Controller\StoricomodificheController
    
    #Commands as services
    cdf.bicorebundle.command.createdatabase:
        class: Cdf\BiCoreBundle\Command\BiCoreBundleCreatedatabaseCommand
        public: false
        tags:
            -  { name: console.command }
            
    cdf.bicorebundle.command.dropdatabase:
        class: Cdf\BiCoreBundle\Command\BiCoreBundleDropdatabaseCommand
        public: false
        tags:
            -  { name: console.command }
            
    cdf.bicorebundle.command.droptables:
        alias: Cdf\BiCoreBundle\Command\BiCoreBundleDroptablesCommand
        public: true
            
    Cdf\BiCoreBundle\Command\BiCoreBundleDroptablesCommand:
        class: Cdf\BiCoreBundle\Command\BiCoreBundleDroptablesCommand
        public: false
        tags:
            -  { name: console.command }

    cdf.bicorebundle.command.install:
        alias: Cdf\BiCoreBundle\Command\BiCoreBundleInstallCommand
        public: true
            
    Cdf\BiCoreBundle\Command\BiCoreBundleInstallCommand:
        class: Cdf\BiCoreBundle\Command\BiCoreBundleInstallCommand
        public: false
        tags:
            -  { name: console.command}

    cdf.bicorebundle.command.pubblicamanuale:
        class: Cdf\BiCoreBundle\Command\BiCoreBundlePubblicamanualeCommand
        public: false
        arguments: ['%kernel.root_dir%']
        tags:
            -  { name: console.command }
            
    cdf.bicorebundle.command.clonaruolo:
        class: Cdf\BiCoreBundle\Command\BiCoreBundleClonaruoloCommand
        public: false
        tags:
            -  { name: console.command }
            
    cdf.bicorebundle.command.configuratorimport:
        alias: Cdf\BiCoreBundle\Command\BiCoreBundleConfiguratorimportCommand
        public: true

    Cdf\BiCoreBundle\Command\BiCoreBundleConfiguratorimportCommand:
        class: Cdf\BiCoreBundle\Command\BiCoreBundleConfiguratorimportCommand
        public: false
        tags:
            -  { name: console.command }

    cdf.bicorebundle.command.configuratorexport:
        alias: Cdf\BiCoreBundle\Command\BiCoreBundleConfiguratorexportCommand
        public: true

    Cdf\BiCoreBundle\Command\BiCoreBundleConfiguratorexportCommand:
        class: Cdf\BiCoreBundle\Command\BiCoreBundleConfiguratorexportCommand
        public: false
        tags:
            -  { name: console.command }
            